In [3]:
import numpy as np
print(np.__version__)

1.26.4


In [7]:
a = np.array([1,2,3,4,5])
print(type(a))
print(a)

<class 'numpy.ndarray'>
[1 2 3 4 5]


In [7]:
np.__version__

'1.26.4'

In [11]:
import numpy
numpy.__version__

'1.26.4'

In [ ]:
np.array

In [5]:
a = np.array([1,2,3,4,5], dtype='int32')

In [7]:
type(a)

numpy.ndarray

In [17]:
tuple_1 = (1,2,3,4,5)
b = np.array(tuple_1)
print(b, type(b))

[1 2 3 4 5] <class 'numpy.ndarray'>


In [19]:
tuple_1 = (1,2,3,4,5)
c = np.array(tuple_1, dtype=float)
print(c, type(c))

[1. 2. 3. 4. 5.] <class 'numpy.ndarray'>


In [89]:
d = np.array([[1,2,3,4,5],[6,7,8,9,10],['a','b','c','d','e']])
print(d.dtype)
print("d is a", str(d.ndim)+"-D object") #use ndim to get the dimension of an object
print("The dimension of d is:", d.shape) #use shape to get the dimensions of an numpy array object
print("Here is what d looks like:", d)
#print("The size of d is:", d.itemsize) ##Not sure where to use this yet
print("d has:", d.size, "elements") #use size to get the total number of elements in an numpy array object
print("d occupies",d.nbytes, "bytes of memory") #use nbytes to calculate memory occupied by an numpty array object

<U11
d is a 2-D object
The dimension of d is: (3, 5)
Here is what d looks like: [['1' '2' '3' '4' '5']
 ['6' '7' '8' '9' '10']
 ['a' 'b' 'c' 'd' 'e']]
d has: 15 elements
d occupies 660 bytes of memory


In [91]:
a

array([1, 2, 3, 4, 5])

In [85]:
a.itemsize

4

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [93]:
d

array([['1', '2', '3', '4', '5'],
       ['6', '7', '8', '9', '10'],
       ['a', 'b', 'c', 'd', 'e']], dtype='<U11')

In [95]:
d[0,1]

'2'

In [97]:
d[1,4]

'10'

In [99]:
d[2,3]

'd'

In [101]:
d[1,]

array(['6', '7', '8', '9', '10'], dtype='<U11')

In [105]:
d[1,:]

array(['6', '7', '8', '9', '10'], dtype='<U11')

In [111]:
d[:,1]

array(['2', '7', 'b'], dtype='<U11')

In [109]:
d[1,1]

'7'

In [113]:
d

array([['1', '2', '3', '4', '5'],
       ['6', '7', '8', '9', '10'],
       ['a', 'b', 'c', 'd', 'e']], dtype='<U11')

In [115]:
d[0,-1]

'5'

In [117]:
d[0,1:-1]

array(['2', '3', '4'], dtype='<U11')

In [119]:
d[0,2:-1]

array(['3', '4'], dtype='<U11')

In [123]:
d[0,1:-1:2]

array(['2', '4'], dtype='<U11')

In [125]:
d[:,0:-2]

array([['1', '2', '3'],
       ['6', '7', '8'],
       ['a', 'b', 'c']], dtype='<U11')

In [129]:
n = [5, 10, 15, 20, 25, 30]
fn = list(filter(lambda x: x > 15, n))
print(fn)

[20, 25, 30]


In [131]:
d

array([['1', '2', '3', '4', '5'],
       ['6', '7', '8', '9', '10'],
       ['a', 'b', 'c', 'd', 'e']], dtype='<U11')

In [135]:
d[0,:] = 555

In [137]:
d

array([['555', '555', '555', '555', '555'],
       ['6', '7', '8', '9', '10'],
       ['a', 'b', 'c', 'd', 'e']], dtype='<U11')

In [169]:
e = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print("e is a", str(e.ndim)+"-D object")
print(e)
print(e.shape)

e is a 3-D object
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
(2, 2, 2)


In [185]:
e[0]

array([[1, 2],
       [3, 4]])

In [173]:
e[1]

array([[5, 6],
       [7, 8]])

In [187]:
e[:,0]

array([[1, 2],
       [5, 6]])

In [189]:
e[0,1]

array([3, 4])

In [159]:
e.ndim

3

In [161]:
e.shape

(1, 3, 2)

In [163]:
e[:,1]

array([[3, 4]])

In [193]:
e[0,1,1]

4

In [195]:
e[0,0,1]

2

In [197]:
e[1,0,1]

6

In [201]:
e[1,1,1]

8

In [209]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [211]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [215]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [229]:
type(np.ones((3,4)))

numpy.ndarray

In [231]:
type(np.ones([3,4]))

numpy.ndarray

In [233]:
np.ones((4,5,6))

array([[[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]]])

In [235]:
np.full((4,4), 100)

array([[100, 100, 100, 100],
       [100, 100, 100, 100],
       [100, 100, 100, 100],
       [100, 100, 100, 100]])

In [237]:
np.full_like(e,-3)

array([[[-3, -3],
        [-3, -3]],

       [[-3, -3],
        [-3, -3]]])

In [241]:
np.random.rand(3,4)

array([[0.91989701, 0.75189554, 0.03221621, 0.34784677],
       [0.45648513, 0.05379022, 0.89260274, 0.54023926],
       [0.55227649, 0.34703302, 0.76488102, 0.02806401]])

In [245]:
np.random.randint(-3,3,size=(10,4))

array([[-1,  1,  0, -3],
       [ 1,  0,  1,  0],
       [ 2, -3, -3,  0],
       [ 1,  0, -1, -1],
       [ 0, -1, -2, -1],
       [ 2,  2,  1, -2],
       [-1,  1,  0, -2],
       [ 2, -3,  2,  0],
       [-1,  0,  1, -1],
       [-3, -3,  0, -3]])

In [247]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [249]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [261]:
arr = np.array([[1,2,3,4]])

In [263]:
arr

array([[1, 2, 3, 4]])

In [265]:
arr.ndim

2

In [279]:
r = np.repeat(arr,3,axis=1)

In [281]:
r

array([[1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4]])

In [275]:
r.ndim

2

In [277]:
r.shape

(3, 4)